### ISSUE TITLE
Minor tweaks to support integration into master branch

### ISSUE THREAD

**Issue by kewashi** [vervallsweg/HousePanel-skin-material#2]
First - thanks for doing this -- it is super cool. In the process of integrating this into the master branch I found a few incompatibility issues that I fixed that are now part of the master branch in the main Open-Dash github repository. This includes a few missing png files for my rock fountain plus some CSS mods needed to make motion sensors show up right. Nothing major. Is there a way for you to include these updates so I can easily merge any future edits you make into the master that would be great.

**Comment by vervallsweg** [comment]
Yeah was wondering what the rock.png does there till I read a code comment somewhere. Will be added in next version. And yes, I'll add version numbers to inform you and user about changes.

**Comment by vervallsweg** [comment]
All of this is fixed in v1.0.0. Somehow I canot find the changes made to the motion sensors. I don't have any, added a virtual one in ST and that one doesn't really work. Well I guess more an issue of the virtual sensor.

Can you maybe post the div of an actually working motion sensor? Just inspect and copy the whole element like:
`<div id="t-6" tile="47" bid="xxxxxxxx-{...}" type="motion" panel="Family" class="thing motion-thing p_47"> {...} </div>`

**Comment by kewashi** [comment]
Here you go...

<div class="overlay motion v_189"><div aid="47" type="motion" subid="motion" title="motion" class="motion office sensor p_189 inactive" id="a-47-motion">inactive</div></div>

**Comment by kewashi** [comment]
Let's try that again...

> <div class="overlay motion v_189"><div aid="47" type="motion" subid="motion" title="motion" class="motion office sensor p_189 inactive" id="a-47-motion">inactive</div></div>

**Comment by kewashi** [comment]
Third time a charm...

`<div class="overlay motion v_189"><div aid="47" type="motion" subid="motion" title="motion" class="motion office sensor p_189 inactive" id="a-47-motion">inactive</div></div>`

**Comment by kewashi** [comment]
Wait... that is a hubitat motion sensor and I didn't get the whole thing. Use this instead:

`<div id="t-85" tile="105" bid="83209fff-0b4a-4b47-b19a-75c5d8822edf" type="motion" panel="Living" class="thing motion-thing p_105 ui-sortable-handle"><div aid="85" title="motion status" class="thingname motion t_105" id="s-85"><span class="n_105">Living Room Motion</span></div><div class="overlay name v_105"><div aid="85" type="motion" subid="name" title="name" class="motion living room name p_105" id="a-85-name">Living Room Motion</div></div><div class="overlay battery v_105"><div aid="85" type="motion" subid="battery" title="battery" class="motion living room battery p_105" id="a-85-battery"><div style="width: 100%" class="ovbLevel L100"></div></div></div><div class="overlay motion v_105"><div aid="85" type="motion" subid="motion" title="motion" class="motion living room p_105 inactive" id="a-85-motion">inactive</div></div></div>`

**Comment by vervallsweg** [comment]
Thanks! So the issue with the motion sensor is the battery that was stuck at the right screen side? Fixed that. If you can confirm that's all ill merge into master.

**Comment by kewashi** [comment]
okay - I pulled the v1.0.0 branch and will test it now

**Comment by kewashi** [comment]
The images directory is gone in the v1.0.0 branch -- is that on purpose?

**Comment by vervallsweg** [comment]
Yes only the wallpapers were stored in that. User can now provide one in the settings panel.

**Comment by kewashi** [comment]
okay... I tried it and motion looks fine. The iframe for weather forecast was formatted wrong so I updated it in the css file. Here is the updated block:

`iframe body {
    margin: 0px;
}
div.frame-thing {
    width: auto !important;
}
div.frame.forecast > iframe {
    width: 500px;
    height: 230px;
    background: none;
}
div.frame-thing {
    /*width: auto;
    height: auto;
    background: none;
    box-shadow: none;*/
}
div.frame-thing div.overlay.status {
    display: none;
}`

**Comment by kewashi** [comment]
full URL is required to set wallpaper... I was expecting a local subdir to also work but it didn't.

Also, the momentary buttons don't seem to click and react. 

Finally, the color picker has an error which makes it look weird. I saw this when I first implemented this library. It has to do with a CSS setting. I don't remember where but I will find it. 

I like what you did with the sliders -- really cool.

**Comment by vervallsweg** [comment]
It does work. Well local subdir if it is on the server obviously, not the client. I've been using local subdirs ever since.

Ok, have no momentary buttons 😅 . Will add that to next release.

Yes color picker has it's own issue #9 and is scheduled for v1.0.1.
I'm adding all of this to the next one because I think fixing them will take some time. But it doesn't break the whole skin.

Thanks, but mdc actually has a [bug](https://github.com/material-components/material-components-web/issues/2269#issuecomment-368906945), thats why the kelvin sliders are not perfect yet. Obviously they're set by kelvin/100 so 2000k = 20 (%) in the slider.

**Comment by kewashi** [comment]
Okay cool - I must not have the files on my rPI. Thought I did but I will double check. Thanks again. I am thinking about not including skins in the master but instead letting skin authors manage their own repo's like you are doing. That might be too hard for some users but it would sure make developers lives easier

**Comment by vervallsweg** [comment]
Does this incorporate the changes to the weather tile?
https://github.com/vervallsweg/HousePanel-skin-material/commit/cc6d1aa20888e2d030473d0ee059f111bacb5360

Need to keep a somewhat equal codebase.

**Comment by vervallsweg** [comment]
Not including skins is also an option. Or you could just pull from the skin master whenever you feel like it, not every time the skin was changed/updated.

**Comment by vervallsweg** [comment]
Ok, just went ahead and merged. v1.0.0 seems pretty usable and #9 and momentary will be fixed in next release in a couple of hours/days.

**Comment by vervallsweg** [comment]
Merged fixes from HP-master.
